# Generated by Django 5.1.5 on 2025-03-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_wishlistcategory_slug_wishlistitem_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=65, unique=True),
        ),
    ]
