# Generated by Django 5.1.5 on 2025-03-05 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_rename_event_name_planner_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='color',
            field=models.CharField(default='#3788d8', max_length=50),
        ),
        migrations.AddField(
            model_name='planner',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='shared_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planner',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
