# Generated by Django 5.1.5 on 2025-03-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_planner_color_planner_friends_planner_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
